name: AWS Overview and RDS
questions:
  - question: What of the following are AWS cloud services?
    options:
      - option: AWS EC2
        correct: true
      - option: AWS S3
        correct: true
      - option: AWS RDS
        correct: true
      - option: AWS ElastiCache
        correct: true
      - option: AWS CloudFormation
        correct: true
      - option: AWS CloudTrail
        correct: true
      - option: AWS CloudWatch
        correct: true
      - option: AWS Lambda
        correct: true
  - question: All AWS services have a free tier
    options:
      - option: "True"
        correct: false
      - option: "False" 
        correct: true
  - question: How can you manage your resources in AWS?
    options:
      - option: AWS Console
        correct: true
      - option: AWS Redshift
        correct: false
      - option: AWS CLI
        correct: true
      - option: AWS SDK (in Python)
        correct: true
      - option: Directly from GitHub
        correct: false
      - option: AWS S3
        correct: false
  - question: You can check the tables of your RDS instance in the AWS Console.
    options:
      - option: "True"
        correct: false
      - option: "False"
        correct: true
  - question: What SQL engines are supported by RDS?
    options:
      - option: MySQL
        correct: true
      - option: PostgreSQL
        correct: true
      - option: Oracle
        correct: true
      - option: MongoDB
        correct: false
      - option: SQLite
        correct: false

