- id: d42a43e6-77a3-46fd-ad3c-96cdb65a39aa
  name: Using AdaBoost with decision trees
  description: |+
    1. Perform AdaBoost using the breast_cancer dataset
    2. Split the data into train and testing using a 0.7:0.3 ratio
    3. Tune the hyperparameters using GridSearch

- id: 9f3ad63d-33c3-451d-a2b7-d98c62f2fc7b
  name: Using AdaBoost without decision trees
  description: |+
    1. Perform AdaBoost using a different base estimator on the breast_cancer dataset
    2. Split the data into train and testing using a 0.7:0.3 ratio
    3. Tune the hyperparameters using GridSearch

- id: e56938f4-767e-4e2c-bde1-db34fecc344c
  name: AdaBoosting regression
  description: |+
    1. Adapt the code from the previous practical to make it work on a regression model
    2. Use the diabetes dataset to train the model
    3. Split the data into train and testing using a 0.7:0.3 ratio
    4. Tune the hyperparameters using GridSearch
