-   id: c9ada592-1c89-4091-8498-643b20e1861a
    name: Rearranging the Rock Paper Scissors Game
    description: |+
        1. In the notebook, go to the last cells and follow the instructions
        2. Make sure you create all the classes and methods you need
    # difficulty: Easy
    # tags: 
    #     - OOP Design
    #     - Classes
    #     - Methods  