name: Principles of OOP Design
questions:
  - question: What are the motivations for using Separation of Concerns? Select all that apply.
    options:
      - option: Keep your code clean
        correct: true
      - option: Improve readability
        correct: true
      - option: Making your code more manageable
        correct: true
      - option: It allows different libraries work with the existing dependencies
        correct: false
      - option: Helping the debugging process
        correct: true
      - option: Keep a concise structure that other developers can use
        correct: true
      - option: None of the above
        correct: false
  # THis question depends on a picture
  # - question: Select everything true about Scopes
  #   options:
  #     - option: We can access variables located in the built-in scope in a nested function
  #       correct: true
  #     - option: If using the global keyword on a local variable, changing the value of that variable locally will affect the value of that variable at a global scope level
  #       correct: true
  #     - option: Inside a nested function, using the keyword nonlocal on a local variable in the nested function will grant access to the global scope
  #       correct: false
  #     - option: Code 1 will print 'Bye!'
  #       correct: false
  #     - option: Code 1 will print 'Hello!'
  #       correct: false
  #     - option: Code 2 will print 'Hello!'
  #       correct: false
  #     - option: Code 2 will throw and error
  #       correct: true
  - question: Select everything true about Namespaces
    options:
      - option: Importing a module to a script will create a new entry for that namespace
        correct: true
      - option: Namespaces are only useful when developing
        correct: false
      - option: Namespaces are only useful when debugging
        correct: false
      - option: There can be only one namespace when running your program
        correct: false
      - option: Built-in is a type of namespace
        correct: true
  - question: Which of the following are included in the 'builtins' module?
    options:
      - option: map
        correct: true
      - option: staticmethod
        correct: true
      - option: frozenset
        correct: true
      - option: re
        correct: false
      - option: filter
        correct: true
      - option: collections
        correct: false
      - option: BaseException.Exception.OSError
        correct: true
      - option: bs4
        correct: false
      - option: pandas
        correct: false
  - question: Select Everything TRUE about OOP design
    options:
      - option: A function or method should contain more than two purposes to save defining multiple functions or methods
        correct: false
      - option: Your functions should be concise and with a single purpose
        correct: true
      - option: If you define a class in a notebook, you can directly import that class in any other notebook or script
        correct: false
      - option: Classes can be used to gather methods with different, yet related, functionalities
        correct: true
      - option: You should use classes only if they gather no more than two methods
        correct: false
      - option: Modules can only contain classes
        correct: false
      - option: Modules can only contain functions
        correct: false
