name: Data transformations - ETL and ELT.
questions:
  - question: Which of the following statements regarding data transformation are True?
    options:
      - option: "Raw data often has issues such as duplicate records and inaccurate or missling information"
        correct: true
      - option: "Data transformation can be defined as moving the data from point A to point B"
        correct: false
      - option: "Data transformation is generally one step of a 3 step process which also involves extracting and loading data"
        correct: true
      - option: "It's not possible to implement data transformation through manually created scripts"
        correct: false
      - option: "Cloud-based data transformation is becoming a major trend in the data engineering space"
        correct: true
      - option: "There are ready made, out-of-the-box tools that can be used to implement data transformation"
        correct: true
  - question: Which of the following statements regarding the Emirates Airlines check-in system are True?
    options:
      - option: "Depositing the XML files into Hadoop is an example of data transformation"
        correct: false
      - option: "Changing the format of data files from XML to Parquet is an example of data transformation"
        correct: true
      - option: "Joining multiple files from several HDFS folders into one file is an example of data transformation"
        correct: true
      - option: "Removing duplicate Parquet records is an example of data transformation" 
        correct: true
      - option: "Exploring the files stored in HDFS can be considered a part of data transformation activities"
        correct: true
  - question: Which of the following statements regarding the types of data transformation commonly used are False?
    options:
      - option: "Connecting a data pipeline to Hadoop HDFS is a type of data transformation"
        correct: false
      - option: "Removing records with NULL values from a dataset is a type of data transformation" 
        correct: true
      - option: "Adding a new column that calculates the Total Daily Sales to a dataset is an example of data transformation"
        correct: true
      - option: "Removing duplicate records from a file is an example of data transformation" 
        correct: true
      - option: "Dropping/deleting an entire database table is an example of data transformation" 
        correct: false
  - question: Which of the following statements regarding the extrct, transform and load (ETL) process are True?
    options:
      - option: "ETL is a relatively new process that has only been introduced after 2010"
        correct: false
      - option: "ETL is mainly used when we have large volumes of unstructured data"
        correct: false  
      - option: "A relational database system is an example of a tool data engineers can use for ETL tasks"
        correct: true
      - option: "In ETL, data transformations occur before the files are moved into a data warehouse"
        correct: true
      - option: "Integrating the datasets from the CRM, ERP and Billing systems and cleaning the data can be considered steps in an ETL solution"
        correct: true
  - question: Which of the following statements regarding the extract, load and transform (ELT) process are True?
    options:
      - option: "ELT can leverage tools like a big data lake to store all the raw data"
        correct: trie
      - option: "In ELT, we can integrate and clean both structured and unstructured data"
        correct: true  
      - option: "Given the current technology limitations, it's not possible to implement ELT activities in the cloud"
        correct: false
      - option: "Hadoop HDFS is an example of an ELT component that can be used to capture and store raw data"
        correct: true  
      - option: "ELT approaches and tools have been commonly used for over two decades"
        correct: false
      - option: "A data warehouse tool such as Amazon Redshift can be used for both ETL and ELT operations"
        correct: true