name: 2.2.6 Hyperparameters, grid search and k-fold cross validation
questions:
  - options:
      - correct: true
        option: Parameters that can be hard to learn from data
      - correct: true
        option: Parameters that we cannot optimize based on data
      - correct: true
        option: Parameters that control the learning process
      - correct: false
        option: Parameters that can not be solved for analytically
    question: Which of the following define hyperparameters?
  - options:
      - correct: true
        option: Learning rate
      - correct: false
        option: Weights
      - correct: false
        option: Bias
      - correct: true
        option: Batch size
      - correct: true
        option: Model choice (including architecture)
      - correct: true
        option: Optimisation algorithm
      - correct: false
        option: Dataset labels
      - correct: false
        option: Dataset features
      - correct: true
        option: Loss function
    question: Which of the following are considered hyperparameters?
  - options:
      - correct: true
        option: Domain knowledge and grid search with small grid
      - correct: false
        option: Testing every combination for 1024 binary hyperparameters
      - correct: true
        option: '"Informed guesses" coming with experience and fine-tuning with grid
          search or similar methods'
      - correct: false
        option: Randomly shooting without any prior knowledge
      - correct: false
        option: Use gradient descent
    question: What are the reasonable options to find hyperparameters?
  - options:
      - correct: false
        option: Automatically finding model parameters
      - correct: true
        option: Automatically finding model hyperparameters
      - correct: true
        option: To exhaustively test combinations of possible hyperparameters defined
          by a human
      - correct: false
        option: Generating probable hyperparameters without any human intervention
    question: What is grid search used for in machine learning?
  - options:
      - correct: false
        option: It is faster
      - correct: true
        option: We have a small dataset
      - correct: true
        option: Usually the results are more reliable
      - correct: false
        option: We can be sure our model is the best with respect to our metric when
          tested on test set
      - correct: false
        option: It is the ultimate machine learning hyperparameter finding method
      - correct: false
        option: Our dataset is too large for simple cross validation
    question: Why should we use K-Fold cross validation instead of simple cross validation?
  - options:
      - correct: false
        option: In case our data has a lot of outliers
      - correct: true
        option: In case our targets are imbalanced
      - correct: false
        option: Always
      - correct: false
        option: When we want to work with time series
      - correct: false
        option: It works like LOOCV (you should look this up), hence to have even
          more reliable validation results
    question: When should we use stratified K-Fold cross validation?
