name: Data for ML
questions:
  - question: Select everything true about sklearn
    options:
      - option: sklearn is a python package for machine learning
        correct: true
      - option: sklearn is a python package for data mining
        correct: false
      - option: sklearn can work with both numerical and categorical data
        correct: true
      - option: sklearn provides toy datasets
        correct: true
      - option: Amongst the models in sklearn, you can find classifiers, regression models and clustering models
        correct: true

  - question: Which of the following are not sklearn modules?
    options:
      - option: sklearn.datasets
        correct: false
      - option: sklearn.linear_model
        correct: false
      - option: sklearn.regression_tree
        correct: true
      - option: sklearn.neighbors
        correct: false
      - option: sklearn.classification
        correct: true

  - question: Which of the following are not clustering classes in sklearn?
    options:
      - option: AffinityPropagation
        correct: false
      - option: MeanShift
        correct: false
      - option: DBSCAN
        correct: false
      - option: PCA
        correct: true
      - option: KNN
        correct: true
  
  - question: Which of the following are not methods for the Logistic Regression in sklearn?
    options:
      - option: fit
        correct: false
      - option: predict
        correct: false
      - option: fit_predict
        correct: true
      - option: score
        correct: false
      - option: sigmoid
        correct: true
      - option: predict_proba
        correct: false

  - question: Select everything true about the iris dataset
    options:
      - option: The iris dataset is a classification dataset
        correct: true
      - option: It has 200 samples
        correct: false
      - option: It has 3 features
        correct: false
      - option: It has 3 classes
        correct: true
      - option: Each class has 50 samples
        correct: true
      - option: By default, it is a dictionary
        correct: true
