- id: 75137b46-fd01-4b09-ac73-ad29d6090f3d
  name: Default Dictionaries
  description: |+
    1. Look information about default dictionaries in Python. 
    2. What is the average time complexity for creating it?
    3. Get familiar with defaultdict! We will be using it during the course
  # difficulty: Basic
  # tags:
  #   - Collections
  #   - defaultdict
- id: 650e493a-b0a6-4dce-b4c2-ad9cb2b4337b
  name: Counter
  description: |+
    1. Look information about Counter in Python
    2. What is the average time complexity for creating it?
  # difficulty: Basic
  # tags:
  #   - Collections
  #   - Counter
- id: 9a113354-2f54-4760-8c8c-7ed1e968c69e
  name: Small o notation
  description: |+
    1. Look information about small o notation
  # difficulty: Basic
  # tags:
  #   - Time Complexity
  #   - Small o
- id: f26d946b-abf3-41c9-a3c2-70b028b46a0c
  name: Small ω notation
  description: |+
    1. Look information about small ω notation
  # difficulty: Basic
  # tags:
  #   - Time Complexity
  #   - Small ω 
- id: a075bfc5-c2c7-45cb-a064-54f4a9977652
  name: Processing a text file with a O(1) space complexity
  description: |+
    1. Create a function which reads in a text file of any size, where each line corresponds to a person and its favourite colour
    2. You have to create a dictionary that counts the frequency of each colour
    3. Use a context manager to open the text file
    4. Without using Counter, store the frequency of each colour in a dictionary 
    5. Your solution should have a space complexity of O(1)
  # difficulty: Basic
  # tags:
  #   - Space Complexity
  #   - Dictionary