name: Intro to feature stores
questions:
  - question: What are some of the main uses of Feature Stores?
    options:
      - option: Store features across multiple projects
        correct: true
      - option: Store features across multiple environments
        correct: true
      - option: Keep information about the metada of a model
        correct: false
      - option: Store features across multiple users
        correct: true
      - option: Avoid duplicate features
        correct: true
      - option: Orchestration of ETL processes
        correct: false
      - option: Avoid recomputing complicated features
        correct: true
      - option: Stream data to a database
        correct: false
  - question: What are examples of Feature Stores providers?
    options:
      - option: Homebrew
        correct: false
      - option: Feast
        correct: true
      - option: Hopswork
        correct: true
      - option: Neptune
        correct: false
      - option: Spark
        correct: false
      - option: Tecton
        correct: true
      - option: TensorFlow
        correct: false