id: 96a873c0-3f66-455d-b672-41c29ca73f0d
name: Lists and Sets
questions:
- answer: 'Observe the error, is x a list, tuple or a disctionary? That means that
    the variable you are trying to index doesn''t have more than one element, probably
    at some point in your code you change the value of x.


    If you have a set, yes, you have more than one element, but sets are unordered,
    so you can''t say that an element is at nth position, so you can cast your set
    into a list by writing "x = list(x)"'
  created_at: '2022-02-02 03:39:10'
  id: 9771d271-bff0-495a-a033-ac748bc297a6
  question: 'I am trying to get the nth element of my list, but I get this error:
    x object is not subscriptable'
