- id: e00891b0-b766-4047-b5b2-03e6c26a5383
  name: Decipher the code
  description: |+
    1. You have the following variable text = 'N&!}!e}*{@v#{%{e*%%@r@%%# {&&*g!*{@o*#&#n*{&{n{}{{a}%{{ {!##g*}*&i%&@!v*}@&e!}!{ %}*%y#@!&o!*@#u&{{} *#*%u}{#&p@@*{ &#!#n@{{&e@}{%v@{}@e%@&}r%@&& #%!}g&#!}o&}@%n*%%#n*%!!a&#@! {@{@l&!*#e!##%t{*{& %&&!y&}##o{*#%u%*{# }*@}d#@}%o@@&}w%!!!n}!&#'
    2. Remove the special characters from the string
    3. Remember not to remove the whitespaces

- id: 37b50c0a-f2df-452d-aba4-3a9dc66cf659
  name: Look for a valid PIN code
  description: |+
    1. Create a function that validates whether a PIN code is valid or not
    2. The PIN code should only contain 4 digits OR 6 digits
    3. You can go to the notebook to see a template that you can use to attempt the exercise

- id: ed9afa52-683b-49ce-af5b-e7772afdca9e
  name: Look for a valid telephone number
  description: |+
    1. Create a function that validates whether a telephone number is valid or not
    2. The number has the following format "(123) 456-7890"
    3. You can go to the notebook to see a template that you can use to attempt the exercise
