- id: dde0f4b3-3b85-4933-95fa-f1c6c446b32a
  name: Get started with Feast
  description: |
    1. Create a Folder anywhere in your computer
    2. Create a new virtual environment
    3. Install Feast by running 'pip install feast'
    4. Run 'feast init' to create a new Feast project in the folder you created
    5. Go to the directory that has been created for you, and observe the files inside it
    6. Run 'feast apply' to apply the Feast project and create offline and online features
    7. cd into the parent directory of the Feast project
    8. Create a new file for accessing the offline features
    9. Create a new file for accessing the online features

- id: a6de4b0c-1cb3-49c9-a18b-562e79577614
  name: Driver ranking with Feast
  description: |
    Work through the driver ranking tutorial provided by Feast 
      - https://docs.feast.dev/tutorials/driver-ranking-with-feast

- id: 597e8c29-13c6-409d-a050-c18a784246bd
  name: Fraud detection with Feast
  description: |
    Work through the fraud detection tutorial provided by Feast 
      - https://docs.feast.dev/tutorials/fraud-detection