name: DVC
questions:
  - question: What are some of the main characteristics of Feast?
    options:
      - option: Integration with AWS services
        correct: true
      - option: Integration with Google Cloud services
        correct: true
      - option: Plotting metrics of the performance of a model
        correct: false
      - option: ETL services
        correct: false
      - option: Create both online and offline features
        correct: true
  - question: What of the following are commands of Feast?
    options:
      - option: init
        correct: true
      - option: checkout
        correct: false
      - option: pull
        correct: false
      - option: apply
        correct: true
      - option: push
        correct: false
      - option: teardown
        correct: true
      - option: materialize
        correct: true