name: MLOps
questions:
  - question: Which of the following are motivations for MLOps?
    options:
      - option: Break down silos between teams
        correct: true
      - option: Define a standardised toolkit
        correct: true
        reason: Standardisation can help teams to work faster and share a common language
      - option: Put larger models into production
        correct: false
        reason: This isn't really part of MLOps
      - option: Leverage common systems and processes across teams to provide economies of scale
        correct: true
      - option: Abstract away engineering tasks so that specific roles can focus on what they are good at. E.g. data scientists can focus on data science rather than having to manage the deployment too.
        correct: true
      - option: Problems can be resolved faster when everyone is used to the same language and system
        correct: true
      - option: Moving from batch processing to streaming
        correct: false
      - option: Deploying neural network based models can be easier thanks to MLOps
        correct: false
  - question: Which of the following would only be present in a machine learning system, but not in a traditional software stack
    options:
      - option: Data versioning
        correct: true
        reason: It's important to version data so that you can understand which data produced a particularly good, bad or interesting model
      - option: Data warehouse storage
        correct: false
        reason: Many non-ML projects require tabular data storage
      - option: Retraining
        correct: true
        reason: ML systems that work well now won't necessarily work later, so we need some way to trigger retraining them
  - question: In which parts of the ML engineering pipeline can MLOps be applied and provide benefits?
    options:
      - option: Data collection
        correct: false
      - option: Model deployment
        correct: false
      - option: Evaluating ML model experiments
        correct: false
      - option: Feature creation and storage
        correct: false
      - option: Model monitoring
        correct: false
      - option: All of the above
        correct: true
  - question: Which of the following things are typically considered to fall under MLOps when working in an ML team?
    options:
      - option: Creating and maintaining good documentation
        correct: true
      - option: Implementing CI-CD to deploy models
        correct: true
      - option: Defining standard processes for repeated operations (e.g. deploying models, adding new features)
        correct: true
      - option: Fine tuning pre-trained machine learning models
        correct: false
      - option: Ingesting streaming and batch data
        correct: false
      - option: Replacing manual processes with automations
        correct: true
  - question: Which of the following are typical parts of the MLOps stack?
    options:
      - option: Feature stores
        correct: true
      - option: Documentation
        correct: true
      - option: Deep learning models
        correct: false
      - option: Model monitoring & observability
        correct: true
      - option: Harware acceleration
        correct: false
      - option: Standardised business processes
        correct: true