id: 63e68dba-8efa-46cd-a495-f7597bf8c9fe
name: Intro to Airflow
questions:
- answer: Apache Airflow has several issues with Windows. If you are using Windows
    and want to use Airflow, we recommend you to finally switch to Linux, where Airflow
    runs much smoother
  created_at: '2022-02-02 03:39:10'
  id: f53c8099-6dd3-4b92-a737-5227edb9578f
  question: "I am trying to install Apache Airflow on Windows 10 at the moment. \n\
    \nWhen used pip install apache-airflow on an Ubuntu instance via Windows, I get\
    \ a bunch of compatibility errors shown. \n\nAny ideas as to what could be done\
    \ to deal with these errors? "