name: Airflow
questions:
  - question: What are some of the motivations for using Airflow?
    options:
      - option: Orchestrating a series of tasks
        correct: true
      - option: Streaming large amounts of data
        correct: false
      - option: Programmatically deploying a ML model based on user defined of metrics
        correct: true
      - option: Creating a workflow for performing ETL
        correct: true
      - option: Hosting a web application framework
        correct: false
      - option: Running a test suite before deploying your program
        correct: true
  - question: Select everything True about Airflow
    options:
      - option: Airflow works on the main programming languages, such as Python, Java, and C
        correct: false
      - option: In the same DAG, the same task can only be ran once
        correct: true
      - option: The scheduler will run even after you restart your computer
        correct: false
      - option: The dummy operator is a wildcard to run any type of operation
        correct: false
      - option: Unless specified, if the start date has passed, Airflow will run a backfill 
        correct: true
      - option: You can change variables, Xcoms, and connectors from either the CLI, or the UI
        correct: true
      - option: You can run Airflow both locally and in Docker
        correct: true
  - question: What are alternatives to Airflow?
    options:
      - option: Luigi
        correct: true
      - option: Docker
        correct: false
      - option: Bash and crontab
        correct: true
      - option: AWS Step Functions
        correct: true
      - option: Caffe
        correct: false
      - option: CloudReactor
        correct: true
      - option: MLFlow
        correct: false
  - question: Consider the following DAG 'task_0 >> [task_1a, task_1b, task_1c] << task_2'. If you keep the default configuration, in what order will the tasks run?
    options:
      - option: task_0 -> task_1a -> task_1b -> task_1c -> task_2
        correct: false
      - option: task_0 + task_2 -> task_1a + task_1b + task_1c 
        correct: false
      - option: task_0 -> task_2 -> task_1a + task_1b + task_1c 
        correct: false
      - option: task_0 -> task_2 -> task_1a -> task_1b -> task_1c 
        correct: true
      - option: task_2 -> task_0 -> task_1a + task_1b + task_1c 
        correct: false
      - option: task_2 -> task_1a -> task_1b -> task_1c -> task_0
        correct: false

