name: Data Visualisation
questions:
  - question: What is the lifecycle of a typical data science project?
    options:
      - option: Data cleaning, Exploratory Data Analysis, Model Training and Testing, Results Analysis
        correct: true
      - option: Data cleaning, Data Presentation, Exploratory Data Analysis
        correct: false
      - option: Exploratory Data Analysis, Data cleaning, Model Training and Testing, Results Analysis
        correct: false
      - option: Model Training and Testing, Exploratory Data Analysis, Data cleaning, Results Analysis
        correct: false

  - question: Why would you want to perform EDA?
    options:
      - option: For checking for missing data
        correct: true
      - option: For checking for outliers
        correct: true
      - option: For gaining insight into the dataset
        correct: true
      - option: For checking for correlations
        correct: true

  - question: Which of the following are not components of EDA?
    options:
      - option: Data cleaning
        correct: true
      - option: Anomaly Detection
        correct: false
      - option: Statistical Analysis
        correct: false
      - option: Results analysis
        correct: true
      - option: Hyperparameter Tuning
        correct: true
  
  - question: Which of the following are visualization libraries in python?
    options:
      - option: Matplotlib
        correct: true
      - option: Seaborn
        correct: true
      - option: Numpy
        correct: false
      - option: Bokeh
        correct: true
      - option: Plotly
        correct: true

  - question: Which of the following are methods from the plotly.express library?
    options:
      - option: scatter
        correct: true
      - option: histogram
        correct: true
      - option: bar
        correct: true
      - option: line
        correct: true
      - option: area
        correct: true