name: Prometheus
questions:
  - options:
      - correct: true
        option: "="
      - correct: true
        option:  "!="
      - correct: true
        option: "=~"
      - correct: true 
        option: "!~"
      - correct: false
        option: "=="
      - correct: false
        option: "~/"
      - correct: false
        option: "**"
    question: Prometheus allows use to comparison operators via regex matching which are valid operators?
  - options:
      - correct: true
        option: Range vectors are created by slicing a timeseries based on time duration.
      - correct: true
        option: Offset allows you to graph a metric at a specified point in time.
      - correct: false
        option: The ordering of time units doesn't matter.
      - correct: false
        option: rate(<metric>[5m, offset 1w]) will return metrics one week ago
      - correct: true
        option: rate(<metric>[5m] offset 1w) will return metrics one week ago
      - correct: false
        option: The smallest unit of time for range selection is seconds.
    question:  Mark all that are true about Range vector selection.
  - options:
      - correct: true
        option: Vector matching defines one instant vector can be matched to another one.
      - correct: true
        option: The labels of each vector need to match.
      - correct: false
        option: The labels of each vector don't need to match.
      - correct: true
        option: "On allows you to specify the labels to match"
      - correct: false
        option: You can't match vectors unless they have the exact same labels. 
      - correct: false
        option: You can match vectors with different value types.
    question: Which is true about vector matching with Prometheus.
  - options:
      - correct: true
        option: stddev
      - correct: true
        option: avg
      - correct: true
        option: count_values
      - correct: true
        option: topk
      - correct: false
        option: middlek
      - correct: false
        option: topquantile
      - correct: false
        option: all
      - correct: false
        option: inf
      - correct: false
        option: merged
    question: Select the aggregation operations which Prometheus can use to aggregate data.
