id: 4223a361-1776-424d-a561-1f8fb0260862
name: Functions
questions:
- answer: 'This question can be answered from the technical perspective, or from a
    perspective that wants to keep a code clean and friendly user. Let''s start with
    the possible technical issues


    If you can''t turn your code into a function, make sure you are following the
    right syntax: use the "def" keyword, use parentheses to define the arguments if
    any, don''t forget the colon, and then, don''t forget the right indentation


    Now, if you want to create a function to make your code cleaner and nicer, there
    is a very good principle for that: separation of concerns. Your function should
    do something tangible, with a specific use. For example, a function that downloads,
    cleans, and uploads data does too many things. It would be worth separating it
    into its concerns: one function for downloading data, another for cleaning data,
    and another for uploading data. That way, it will be easier to do these three
    things separately, and at the same time, doing all three in sequence won''t affect
    the performance of the code'
  created_at: '2022-02-02 03:39:11'
  id: 1c68dc1f-526c-474e-800b-1a7f681647a7
  question: I am having some problems when trying to make my code into a function.