id: 86076c6d-6df5-4c14-8f5e-7d3dfe661de6
name: Git & GitHub
questions:
- answer: "First of all, if you are on Mac or Linux, you won't see gitbash, because\
    \ the default terminal on both OSs already use bash, so there is no need to install\
    \ gitbash. \n\nIf you are on Windows, make sure you have installed gitbash, and\
    \ then restart VSCode"
  created_at: '2022-02-02 03:39:10'
  id: dc6636e9-04cc-4f6c-bb09-17667f376a01
  question: I Can't find git bash in the terminal dropdown in VSCode
- answer: 'You can make pushes even when you haven''t commited anything yet. Of course,
    if you haven''t commited anything, you won''t push anything. So make sure you
    commit all the files you want to push to github, and retry git push


    If that doesn''t work, make sure that you are pushing to the right repository.'
  created_at: '2022-02-02 03:39:10'
  id: 224cdf8f-f9a6-4192-ac0c-e438878ce3a3
  question: When I run git push, it  doesn't seem to work. It says it worked but the
    files don't appear on GitHub
- answer: 'You need to understand that git and GitHub are not the same! git allows
    you to keep record of your files, by observing the changes that have taken place
    over time. On the other hand, GitHub stores that information, so many users can
    access it


    With that in mind, remember that commands that you run on your computer can affect
    both applications. For example, git add, and git commit will change the local
    repository, but git push will save the commited files to the remote repository
    (GitHub in this case). So when you work locally, you can add and commit as many
    times as you want, unless you don''t make a push, none of these changes will be
    reflected on GitHub. '
  created_at: '2022-02-02 03:39:10'
  id: 9b03d67d-0bb7-4e75-8016-905b5e76793b
  question: I know the git commands but I don't know how to align it with my github
    online account.