name: Data ingestion principles
questions:
  - question: Which of the following can be data sources/origins for a digital data pipeline?
    options:
      - option: "An Oozie workflow"
        correct: false
      - option: "Staff at the check-out counter in a supermarket"
        correct: true
      - option: "Smart car"
        correct: true
      - option: "An Oracle database"
        correct: true
      - option: "Hadoop HDFS"
        correct: true
      - option: "The hand-written meeting notes"
        correct: false
  - question: Which of the following statements about the components of an enterprise data pipeline are True?
    options:
      - option: "We always require a data source to produce the data"
        correct: true
      - option: "There are usually 8 system components types in total"
        correct: false
      - option: "Data transformation and data cleaning are important parts of the pipeline"
        correct: true
      - option: "Data storage (also called landing zones) can be removed to increase the efficiency of the pipeline" 
        correct: false
      - option: "Due to current technology limitations, it's not yet possible to perform basic data processing tasks while the data is in motion"
        correct: false
  - question: Which of the following statements about approaches to data ingestion are False?
    options:
      - option: "Batch data ingestion is the most modern form currently used"
        correct: false
      - option: "Streaming and micro-batch are similar but not identical" 
        correct: true
      - option: "The classification of the data ingestion approaches is based only on the volume of data being handled"
        correct: false
      - option: "It's possible to have a tool that can handle both batch and streaming data" 
        correct: true
  - question: Which of the following are challenges faced when designing and implementating a data pipeline?
    options:
      - option: "Data security"
        correct: true
      - option: "Handling a variety of data formats"
        correct: true  
      - option: "IP address of the cloud cluster"
        correct: false
      - option: "Data can be lost or corrupted during transfer"
        correct: true
      - option: "Data visualization dashboard licenses expiration dates"
        correct: false    
  - question: Which of the following statements regarding the industry best practices for designing and deploying data pipelines are True?
    options:
      - option: "It's recommended to keep the data stored in one large file rather than in smaller seperate files to avoid storage complexity"
        correct: false
      - option: "To enhance network bandwidth, it's suggested to keep all tools on one main cluster"
        correct: false  
      - option: "Using data pipeline automation tools like Apache Airflow helps improve the efficiency of the pipeline"
        correct: true
      - option: "Network bandwidth is not a major concern for data engineers since it'll be handled by the DevOps team"
        correct: false  
      - option: "Leveraging parallelism results in increasing the job times"
        correct: false
      - option: "It's recommended to process large volumes of data while it's in-place, rather than while it's in-motion"
        correct: true 