- name: Using kafka
  id: 19e9bf02-17b7-4e1d-8add-78c385aa8ca5
  description: |+
    1. Check out how to link Spark Streaming with Kafka https://spark.apache.org/docs/2.1.0/streaming-kafka-0-8-integration.html
    2. Create a Kafka topic
    3. Create a Spark Streaming job that reads from the topic and prints the messages to the console
    4. Run the job

- name: Using Additional Receivers
  id: e7544460-592f-454a-8e82-77e3b5d8a21a
  description: |+
    1. Check out additional receivers https://spark.apache.org/docs/latest/streaming-custom-receivers.html
    2. Follow the example in the URL. Don't run anything, since you would need to use Scala or Java! Simply understand the steps for future reference.
    3. When creating a custom receiver, what kind of receivers can you create?
