name: Kafka Overview
questions:
  - question: Which of the following are Apache Kafka components?
    options:
      - option: "Brokers"
        correct: true
      - option: "Consumers"
        correct: true
      - option: "Hadoop HDFS"
        correct: false
      - option: "Topics"
        correct: true
      - option: "Spark"
        correct: false
      - option: "AWS"
        correct: false
  - question: Which of the following statements are True about Kafka?
    options:
      - option: "Kafka uses a Client-Server type architecture"
        correct: true
      - option: "Zookeeper is not required in any Kafka system"
        correct: false
      - option: "Kafka is often suitable for smaller companies who have less data, but can present problems to companies with Big Data"
        correct: false
      - option: "Kafka is not well designed for real-time streaming data" 
        correct: false
      - option: "Kafka is a closed-source and expensive technology"
        correct: false
  - question: Which of the following statements are False about the Kafka Topology
    options:
      - option: "We can only have one Producer per Kafka cluster"
        correct: false
      - option: "For every Producer in the system, we can only have one Consumer" 
        correct: false
      - option: "Zookeeper is a direct component of Kafka and not a 3rd party tool"
        correct: false
      - option: "A Topic is used to store data records in Kafka" 
        correct: true
  - question: Which of the following statements are True regarding the Kafka Use Cases
    options:
      - option: "Kafka can't be used in the Financial sector as it's not a regulated technology"
        correct: false
      - option: "Kafka is not well designed for batch data processing in the Airlines industry"
        correct: false  
      - option: "Kafka has successfully been used as part of a Recommendation Engine technology"
        correct: true
      - option: "The limitations of Kafka prevent it from being used in Stock Trading"
        correct: false  
  - question: Select the main roles that Zookeeper plays in a Kafka system
    options:
      - option: "Storing Data"
        correct: false
      - option: "Election of the Contoller node"
        correct: true  
      - option: "Managing the Access Control List"
        correct: true
      - option: "Producing data for the cluster"
        correct: false  
      - option: "Topic Configuration"
        correct: true
      - option: "Membership of the Cluster"
        correct: false 