name: Batch and streaming data
questions:
  - question: Which of the following statements regarding batch data ingestion and processing are True?
    options:
      - option: "Batch data ingestion is used when the data volume that needs to be ingested is small and the required data velocity is very fast"
        correct: false
      - option: "Batch data processing involves handling new and older, historical data"
        correct: true
      - option: "The more modern form of data ingestion global companies leverage is batch"
        correct: false
      - option: "Extracting data from a database and sending it to a Hadoop HDFS data lake is an example of batch data ingestion"
        correct: true
      - option: "Kafka can be used as a batch data ingestion tool"
        correct: true
      - option: "Spark Streaming is an example of a batch data processing framework"
        correct: false
  - question: Which of the following statements regarding databases and data warehouses are True?
    options:
      - option: "A database and a data warehouse are identical, serve the same purpose and the terms can be used interchangeably"
        correct: false
      - option: "A data warehouse system is a sub-component of a database system"
        correct: false
      - option: "Data modelling, data normalization and schemas are important data warehouse concepts"
        correct: true
      - option: "Normalization is the process of creating larger, integrated tables with several redundancies of data records" 
        correct: false
      - option: "An OLAP cube is optimized for processing transactional data in organisations"
        correct: false
  - question: Which of the following statements regarding the batch processing tools are False?
    options:
      - option: "Hadoop HDFS is a popular tool for big data storage"
        correct: true
      - option: "Apache Storm is widely used a batch data processing framework in global companies" 
        correct: false
      - option: "Hive is a big data warehouse that can query data using a SQL-like language"
        correct: true
      - option: "Spark only supports streaming/real-time data processing, but not batch" 
        correct: false
  - question: Which of the following statements regarding Streaming/Real-time data processing are True?
    options:
      - option: "Streaming data processing is the oldest form of data processing and has been used for a long time."
        correct: false
      - option: "All real-time processing is streaming, but not all streaming is real-time"
        correct: true  
      - option: "Flume and Kafka are examples of tools that can be used to ingest streaming data"
        correct: true
      - option: "Spark Streaming and Storm are data processing frameworks that can be used to handle real-time streaming data"
        correct: true
      - option: "Streaming data pipelines can connect to various data consumers such as Hadoop HDFS and database systems"
        correct: true
  - question: Which of the following statements regarding the comparison between batch and streaming data are True?
    options:
      - option: "The approach that requires the most disk storage space is Streaming"
        correct: false
      - option: "In Batch, it's acceptable to have a data processing job that requires 2 days to run"
        correct: true  
      - option: "Streaming data requires millisecond(s) or second(s) performance"
        correct: true
      - option: "If a company wants to analyze the sales for an entire month, it should use a streaming data processing approach"
        correct: false  
      - option: "The CEO of a company wants to see the inventory of all products with a few minutes delay at most.  He should use a streaming system"
        correct: true
      - option: "Both streaming and real-time data tools can process extremely large volumes of data without any major issues"
        correct: false 
