- id: 1e2fc2c8-d70e-435d-94b4-6363d79eb2e0
  name: Publish your first package
  description: The whole notebook is a walkthrough of the process of publishing a package. Go to the notebook and follow the steps.
  # difficulty: Medium
  # tags: 
  #   - Testing
  #   - Software Design
  #   - Project Structure
  #   - Pypi
  #   - Packages