#!/bin/bash
export NETCAT_CALLS=$(history | grep -e "nc -lk 8000$" -c)
export NUMBER_INPUT_IMAGES=$(aws s3api list-objects --bucket ${BUCKET} | grep "input.png" -c)
export NOHUP_CALLS=$(history | grep "nohup" -c)
export PYTHON_BACKGROUND=$(ps | grep "python" -c)
export IP_DIG=$(history | grep -e "@resolver1.opendns.com$" -c)
echo "Checking Milestone 1"
python3 -m image-segmentation-test.test_milestone1_p1 2> milestone1_p1.txt
RESULT_M1_P1=$?
RESULT_M1_P2=1
RESULT_M2=1
RESULT_M3=1
RESULT_M4=1
if [ $RESULT_M1_P1 -eq 0 ]; then
    python3 -m image-segmentation-test.test_milestone1_p2 2> milestone1_p2.txt
    RESULT_M1_P2=$?
    python3 -m image-segmentation-test.verify_milestone1_p2
else
    python3 -m image-segmentation-test.verify_milestone1_p1
fi

if [ $RESULT_M1_P2 -eq 0 ]; then
    echo "Checking Milestone 2"
    python3 -m image-segmentation-test.test_milestone2 2> milestone2.txt
    RESULT_M2=$?
else
    echo "Revise Milestone 1 to continue"
fi

python3 -m image-segmentation-test.verify_milestone2

if [ $RESULT_M2 -eq 0 ]; then
    echo "Checking Milestone 3"
    aws s3api list-objects --bucket ${BUCKET} | grep output.png > output_files.txt
    aws s3api list-objects --bucket ${BUCKET} | grep input.png > input_files.txt
    python3 -m image-segmentation-test.test_milestone3 2> milestone3.txt
    RESULT_M3=$?
fi

python3 -m image-segmentation-test.verify_milestone3

if [ $RESULT_M3 -eq 0 ]; then
    echo "Checking Milestone 4"
    python3 -m image-segmentation-test.test_milestone4 2> milestone4.txt
    RESULT_M4=$?
fi

python3 -m image-segmentation-test.verify_milestone4

if [ $RESULT_M4 -eq 0 ]; then
    echo "Congratulations, you completed the scenario!"
fi

rm *.txt
