- id: 0770db72-c79c-492d-9cd4-845d8f81615c
  name: so what is `.score`?
  description: |
    - look into the sklearn docs and find a classification model
    - which evaluation metric does the `score` method return
    - do the same for a regression model
    - compute these scores for a few different models and datasets and discuss the results

- id: 061fbfbc-9280-4ffd-a59a-66648b62f116
  name: ROC curves
  description: |
    - fit a logistic regression model on the breast cancer dataset
    - plot the ROC curve (look in the docs)
    - calculate the AUC (look in the docs)
    - repeat for several different models
    - repeat for several different classification datasets
    - for each of the datasets, discuss what the operating points of the ROC curve might be?
      - consider both thresholds for performance and whether false negatives or false positives are more costly