name: S3 and boto3
questions:
  - question: What of the following is a valid S3 bucket name? Assume there is no existing bucket with those names.
    options:
      - option: HelloWorld
        correct: false
      - option: catscraper
        correct: true
      - option: ai core
        correct: false
      - option: my_bucket
        correct: false
      - option: Python_Course
        correct: false
      - option: ai-core-test
        correct: true
  - question: Select everything True about S3 buckets
    options:
      - option: S3 buckets are databases
        correct: false
      - option: S3 buckets are data lakes
        correct: true
      - option: You can store any type of data in an S3 bucket
        correct: true
      - option: By setting the bucket public, anyone can download its content
        correct: false
      - option: S3 buckets can have differnt policies to allow its content
        correct: true
  - question: You create a bucket using boto3 by running boto3.create_bucket(Bucket='my_bucket')
    options:
      - option: "True"
        correct: false
      - option: "False"
        correct: true
  - question: What methods are available from the client method to interact with S3 buckets?
    options:
      - option: .put_object()
        correct: true
      - option: .remove_object()
        correct: false
      - option: .get_object()
        correct: true
      - option: .list_files()
        correct: false
      - option: .upload_file()
        correct: true
      - option: .download_file()
        correct: true