- id: 2160e22a-95cf-4373-95e2-98f1cdfc3f24
  name: Hands on with DVC
  description: |
    1. Make sure you understood what Data Versioning is. Go to the previous notebook if you are unsure of it.
    2. Create a new virtual environment (but don't activate it yet!). You can call it `test_dvc`
    3. Install dvc. You can check how to do it in the Installation section
    4. Create an empty repo on GitHub that will store your local repo
    5. If you haven't, create an AWS S3 bucket. You can see how to do it [here](https://github.com/life-efficient/Data-Engineering/tree/main/Module%204.%20Cloud%20Basics/2.%20S3%20and%20boto3)
    6. Go through the notebook and follow all steps.
    7. If you want to get some practice, use a model that you already trained, and try to make pipelines and experiments using DVC, and uploading your tracked results to the cloud.

- id: 2313f414-2185-4a1b-a3dc-27a7556dae09
  name: Data versioning cats and dogs
  description: |
    Work through the cats and dogs example provided by DVC [here](https://dvc.org/doc/use-cases/versioning-data-and-model-files/tutorial)

