name: Bias & Variance
questions:
  - options:
      - correct: false
        option: 'True'
      - correct: true
        option: 'False'
    question: When we say "bias" in machine learning, we are always referring to the
      constant parameter. Like b in y = Xw + b
  - options:
      - correct: true
        option: It corresponds to bias, not variance
      - correct: false
        option: One remedy is collecting more data
      - correct: false
        option: One remedy is training for longer after converging
      - correct: false
        option: One remedy is training with an alternative loss function
      - correct: false
        option: One remedy is to add regularisation
      - correct: true
        option: One remedy is to increase the capacity of our model
      - correct: false
        option: Model performs well on training data
      - correct: false
        option: Model performs well on validation data
      - correct: false
        option: Model performs well on test data
    question: Mark everything true about underfitting
  - options:
      - correct: false
        option: It corresponds to bias, not variance
      - correct: true
        option: One remedy is collecting more data
      - correct: false
        option: One remedy is training for longer after converging
      - correct: false
        option: One remedy is training with an alternative loss function
      - correct: true
        option: One remedy is to add regularisation
      - correct: false
        option: One remedy is to increase the capacity of our model
      - correct: true
        option: Model performs well on training data
      - correct: false
        option: Model performs well on validation data
      - correct: false
        option: Model performs well on test data
    question: Mark everything true about overfitting
  - options:
      - correct: false
        option: bias in model results in variance
      - correct: true
        option: bias in model results in underfitting
      - correct: false
        option: bias in model results in overfitting
      - correct: true
        option: variance in model results in overfitting
      - correct: false
        option: variance in model results in underfitting
    question: Match model phenomena with training phenomena
  - options:
      - correct: false
        option: Large validation-train loss discrepancy
      - correct: true
        option: Large training loss
      - correct: true
        option: Training loss plateaus
      - correct: false
        option: Validation loss plateaus
      - correct: false
        option: Validation loss lower than training loss
      - correct: false
        option: Training loss lower than validation loss
    question: 'Symptoms of too much bias in the model:'
  - options:
      - correct: true
        option: Large validation-train loss discrepancy
      - correct: false
        option: Large training loss
      - correct: false
        option: Training loss plateaus
      - correct: false
        option: Validation loss plateaus
      - correct: false
        option: Validation loss lower than training loss
      - correct: false
        option: Training loss lower than validation loss
    question: 'Symptoms of too much variance in the model:'
  - options:
      - correct: true
        option: Models
      - correct: false
        option: Datasets
      - correct: false
        option: Labels
      - correct: false
        option: Features
      - correct: false
        option: Predictions
      - correct: false
        option: Optimisers
    question: Fill in the blank. \_\_\_ with either high variance or high bias can
      lead to poor performance on the validation set.
  # BELOW QUESTIONS REQUIRE SUPPORT FOR IMAGES
  # - options:
  #     - correct: true
  #       option: Underfitting
  #     - correct: false
  #       option: Overfitting
  #     - correct: true
  #       option: High bias
  #     - correct: false
  #       option: High variance
  #     - correct: false
  #       option: Looks ok
  #   question: The following diagram displays which of the following options?
  # - options:
  #     - correct: true
  #       option: Underfitting
  #     - correct: false
  #       option: Overfitting
  #     - correct: true
  #       option: High bias
  #     - correct: false
  #       option: High variance
  #     - correct: false
  #       option: Looks ok
  #   question: The following diagram displays which of the following options?
  # - options:
  #     - correct: true
  #       option: Underfitting
  #     - correct: false
  #       option: Overfitting
  #     - correct: true
  #       option: High bias
  #     - correct: false
  #       option: High variance
  #     - correct: false
  #       option: Looks ok
  #   question: The following diagram displays which of the following options?
