- id: da852182-239b-4a6a-bccf-f93fbd51cd41
  name: Test your Cart module
  description: |+
    1. Go to the notebook and follow the instructions of the challenge (At the end of the notebook)
  # difficulty: Easy
  # tags:
  #   - Unit Testing
  #   - Integration Testing