name: Testing
questions:
  - question: What are the motivations for testing your program?
    options:
      - option: Check the performance of your program
        correct: true
      - option: Check the possible security breaches of your program
        correct: true
      - option: Check that your program work as expected
        correct: true
      - option: Check that small pieces of your code work as expected
        correct: true
      - option: Check that small pieces of your code can work in tandem as expected
        correct: true
  - question: What of the following are categories of testing?
    options:
      - option: Unit Testing
        correct: true
      - option: Unsupervised Testing
        correct: false
      - option: Integration Testing
        correct: true
      - option: Manual Testing
        correct: true
      - option: Supervised Testing
        correct: false
      - option: Acceptance Testing
        correct: true
      - option: Bottleneck Testing
        correct: false
  - question: What of the following options is a step in TDD cycle? Select all that apply
    options:
      - option: Red - Write a test that is intended to fail
        correct: true
      - option: Red - Write a test that is intended to pass
        correct: false
      - option: Red - Run all tests
        correct: false
      - option: Green - Write a test that is intended to fail
        correct: false
      - option: Green - Write a test that is intended to pass
        correct: true
      - option: Green - Run all tests
        correct: false
      - option: Refactor
        correct: true
  - question: "True or False: You can add up to three assertion in each test"
    options:
      - option: "True"
        correct: false
      - option: "False"
        correct: true
  - question: "True or False: assertRaises() allows you assert an intentional error"
    options:
      - option: "True"
        correct: true
      - option: "False"
        correct: false