id: bf5e1b7b-0556-4417-809a-85e544ba2e0e
name: APIs and requests
questions:
- answer: "We are not going to give you the answer straight away, you will have to\
    \ figure it out! \n\nBut, here's a tip: https://pokeapi.co/api/v2/type/{id or\
    \ name}/ will give you a json object. One of the keys is a list of all the pokemon\
    \ of the type you specify"
  created_at: '2022-02-02 03:39:10'
  id: 1e70ed6b-44df-4b0f-b9ba-3c01fa2a2e79
  question: 'I''m struggling to identify the correct endpoint to use to be able to
    access all psychic pokemon in a JSON that includes a Pokedex ID key '
