name: SQL - Joins
questions:
  - options:
      - correct: false
        option: 'True'
      - correct: true
        option: 'False'
    question: Foreign keys in a table must be unique
  - options:
      - correct: true
        option: 'True'
      - correct: false
        option: 'False'
    question: Primary keys in a table must be unique
  - options:
      - correct: true
        option: 'True'
      - correct: false
        option: 'False'
    question: You CAN only use one table in the FROM statement
  - options:
      - correct: true
        option: 'True'
      - correct: false
        option: 'False'
    question: We use left joins when we want to ensure that all entries in the left
      table appear in the output of the join, even if there is no entry in the right
      table with a corresponding key
  - options:
      - correct: false
        option: It makes the distribution of data resemble more closely the Standard
          Normal distribution
      - correct: false
        option: It reduces the number of tables necessary to keep our data
      - correct: true
        option: It reduces the space that we need to keep our data
      - correct: true
        option: It avoids repetition in each table
    question: Mark the options which are true about database normalisation
  - options:
      - correct: false
        option: When created in the SELECT statement they can be used in the GROUP
          BY statement
      - correct: true
        option: When created in the FROM statement they can be used in the GROUP BY
          statement
      - correct: true
        option: When created in the SELECT statement they can be used in the ORDER
          BY statement
      - correct: true
        option: When created in the FROM statement they can be used in the SELECT
          statement
    question: Mark what's True about aliases
