id: 13308eb8-cd86-4e7e-b91a-271e01020dc9
name: SQL Setup
questions:
- answer: 'Your browser is connected to the localhost, so it doesn''t actually know
    how to get access to your local files. It''s like if you were on a website, so
    even though it''s local, your computer doesn''t know how to get to your files.


    There are two options, you can open the pgadmin application (not the browser),
    and restore the database there. The database will also show up in the browser.


    The other option is to drag the pagila.tar file into the window that pops up when
    looking for a file. '
  created_at: '2022-02-02 03:39:10'
  id: 2252f388-c04f-4f64-8de3-a0a57dcd23ee
  question: When trying to restore the Pagila database on Pgadmin, no files show up