name: SQL - Setup
questions:
  - question: What of the following options are available when you open the Pagila database? Select only those options that are in the first level 
    options:
      - option: Catalogs
        correct: true
      - option: Schemas
        correct: true
      - option: Views
        correct: false
      - option: Columns
        correct: false
      - option: Tables
        correct: false
  - question: What of the following options are available when you open Schemas and then public?
    options:
      - option: Catalogs
        correct: false
      - option: Domains
        correct: true
      - option: Rows
        correct: false
      - option: Columns
        correct: false
      - option: Tables
        correct: true
      - option: Views
        correct: true
  - question: What tables are available in the database?
    options:
      - option: actor
        correct: true
      - option: language
        correct: true
      - option: cinema
        correct: false
      - option: movie
        correct: false
      - option: rental
        correct: true
      - option: country
        correct: true
  - question: What columns are present in the payment table?
    options:
      - option: payment_id
        correct: true
      - option: customer
        correct: false
      - option: staff_id
        correct: true
      - option: rental
        correct: false
      - option: amount
        correct: true
      - option: payment_date
        correct: true