name: Intro to Data Versioning
questions:
  - question: Which of the following can be motivations for using Data Versioning Tools?
    options:
      - option: Create datasets based on engineered features
        correct: false
      - option: Keep track of the version of the data
        correct: true
      - option: Keep track of the metrics of a model
        correct: true
      - option: Keep track of the features used by a model
        correct: false
      - option: Create plots based on experiments
        correct: true
  - question: Which of the following is a good example of a Data Versioning Tool?
    options:
      - option: Data Versioning Control
        correct: true
      - option: Tecton
        correct: false
      - option: Apache Spark
        correct: false
      - option: Pachyderm
        correct: true
      - option: Delta Lake
        correct: true
      - option: Dolt
        correct: true
      - option: AWS Glue
        correct: false