name: 4.2.1 AWS API Gateway
questions:
  - options:
      - correct: true
        option: It's better to gather similar resources under a parent resource, rather
          than have a more "flat" API resource tree
      - correct: false
        option: It's preferable to use GET methods rather than DELETE methods because
          DELETE methods carry permissions which can harm your backend by deleting
          resources without warning
      - correct: false
        option: For each API resource, you should minimise the number of different
          method types it exposes
      - correct: false
        option: Websocket APIs are just an older version of REST APIs
      - correct: false
        option: One API resource can define integrations for several of the same method
          type (e.g. several GETs on the same resource)
    question: API Design
  - options:
      - correct: false
        option: Pricing is based on number of requests
      - correct: false
        option: Can accept incoming requests from arbitrary different sources, including
          those made from Python, or from web application
      - correct: true
        option: Can have arbitrary different integrations on the back end, including
          AWS Lambda, or another API
      - correct: true
        option: API Gateway can control things like rate limits on the number of requests
          made to your API
      - correct: false
        option: There is no default limit to the number of resources on your API
      - correct: false
        option: We should create a new stage each time we deploy the API
    question: Which of the following statements are true about AWS API Gateway?
