version : '3.4'
services:
    model_serving_api:
      build: .
      ports: 
        - 8080:8080
      restart: always
      environment:
        - BUCKET_NAME=${BUCKET_NAME}
      network_mode: host
      volumes: 
        - ~/app:/app