name: Arithmetic Operators and Strings
questions:
  - options:
      - correct: true
        option: 4 / 3 returns a float
      - correct: false
        option: 4 // 3 returns a float
      - correct: false
        option: 4 % 3 returns a float
      - correct: true
        option: The ' + ' operator concatenates two strings
      - correct: true
        option: The ' + ' operator concatenates two lists
      - correct: false
        option: The ' + ' operator concatenates two sets
      - correct: true
        option: The ' + ' operator concatenates two tuples
      - correct: false
        option: Using the ' \* ' operator with two lists of integers of the same length will multiply both lists element-wise
      - correct: true
        option: Using a ' \* ' operator with an integer and a float returns a float
      - correct: true
        option: Using a ' \* ' operator with a list and an integer_ n _concatenates the list _n _times
    question: Mark everything that is TRUE.
  - options:
      - correct: false
        option: a += 1 throws a Syntax error
      - correct: true
        option: a += a is equivalent to writing a = 2 \* a
      - correct: true
        option: a \*= a is equivalent to writing a = a \*\* 2
      - correct: false
        option: a /= a returns an integer
      - correct: false
        option: a /= a is equivalent to writing a //= a
    question: You have an _integer_ named _a_. Mark everything that is TRUE.
  - options:
      - correct: false
        option: Strings are indexed and mutable
      - correct: true
        option: Strings are indexed and immutable
      - correct: false
        option: Strings are unindexed and mutable
      - correct: false
        option: Strings are unindexed and immutable
      - correct: false
        option: '''A'' > ''a'' is True'
      - correct: true
        option: '''Yes'' > ''No'' is True'
      - correct: false
        option: '''Hello'' + ''World'' returns ''Hello World'''
      - correct: false
        option: '''Hello World''.split() returns a string'
    question: 'Mark everything TRUE about strings:'
  - options:
      - correct: true
        option: str\_test.endswith('r')
      - correct: false
        option: str\_test.startswith('t')
      - correct: true
        option: str\_test.istitle()
      - correct: false
        option: str\_test.isalpha()
      - correct: true
        option: str\_test.replace(' ', '').isalpha()
      - correct: true
        option: '''This'' in str\_test'
    question: 'You have the following string

      str\_test = ''This Assessment Is Taking Forever''

      Mark all options that return True:'
  # - options:
  #     - correct: false
  #       option: a)
  #     - correct: true
  #       option: b)
  #     - correct: false
  #       option: c)
  #     - correct: false
  #       option: d)
  #   question: 'You received a long string with '' \_ '' and '' \* '' interleaved randomly
  #     in the string, and a specific deciphering pattern. You want to clean it to get
  #     a usable string. You need to:

  #     1) Remove all the punctuation marks ('' \_ '' and '' \* '')

  #     2) Reverse the second part of the string

  #     3) Concatenate both strings

  #     Select which code(s) in the image would perform that task'
