- id: 49075ed0-45e2-4a3b-b209-f4feca0a101e
  name: Create a simple S3 bucket stack
  description: |
    - create a file called template.yaml
    - define just one resource, the S3 bucket
    - use this to create a cloudformation stack

- id: b24e4382-e32e-4d6d-8106-e58194a873ca
  name: Create the data collection stack
  description: |
    - the stack consists of 4 resources:
      - IAM role with permissions:
        - S3 full access
        - LambdaBasicExecutionRole for logging to cloudwatch
      - lambda function
      - S3 bucket
      - Cloudwatch Rule