name: SQL - Basics
questions:
  - options:
      - correct: true
        option: WHERE col\_name = 'foo'
      - correct: true
        option: WHERE col\_name IN ('foo')
      - correct: false
        option: WHERE col\_name between 'foa' and 'foz'
    question: Which of the following methods could you use to filter for an exact
      match to the value "foo"
  - options:
      - correct: false
        option: WHERE col\_name = 'foo', 'bar'
      - correct: true
        option: WHERE col\_name IN ('foo', 'bar')
      - correct: false
        option: WHERE col\_name = ('foo', 'bar')
      - correct: false
        option: WHERE col\_name between 'baa' and 'foz'
    question: Which of the following methods could you use to filter for an exact
      match to one of the values "foo" or "bar"
  - options:
      - correct: false
        option: WHERE col\_name = 'foo', 'bar'
      - correct: false
        option: WHERE col\_name IN ('foo', 'bar')
      - correct: true
        option: WHERE col\_name BETWEEN 'baa' AND 'foz'
    question: Which of the following methods could you use to filter for a number
      of consecutive values?
  - options:
      - correct: false
        option: WHERE col\_name = 'foo'
      - correct: true
        option: WHERE col\_name = '%foo'
      - correct: true
        option: WHERE col\_name = 'foo%'
      - correct: true
        option: WHERE col\_name = '%foo%'
    question: Which of the following options would you use to return all rows containing, amongst other characters, 'foo' in col\_name
  - options:
      - correct: false
        option: Many choices
      - correct: false
        option: One to many relationship
      - correct: false
        option: Many relationships
      - correct: true
        option: Something to many relationship
    question: What does a crow's foot mean in an ERD?
