id: 6556d991-bdd0-4e97-bfb1-c9355f34a868
name: Dictionaries Tuples and Operators
questions:
- answer: 'KeyError usually means that you are trying to index a key in a dictionary
    that doesn''t contain such key. Read the traceback error, and check your code
    to see why that key doesn''t exist, maybe you wrote a typo? Maybe that specific
    dictionary doesn''t have that key?


    If that error persists, take a look at this page https://realpython.com/python-keyerror/'
  created_at: '2022-02-02 03:39:10'
  id: 6528c3bd-c459-4dfb-9847-33b111e69c90
  question: "I'm trying to run a piece of code from the notebook and I'm getting a\
    \ KeyError. \n\nI have no idea where this is coming from honestly. "