name: Python Programming. Debugging
questions:
  - question: Select everything TRUE about NameError
    options:
      - option: You can get a NameError due to a bad use of the scope
        correct: true
      - option: You can get a NameError due to a missing bracket
        correct: false
      - option: You can get a NameError due to a typo
        correct: true
      - option: Python is case sensitive, and thus, NameError might appear when using a lowercase and an uppercase variable
        correct: true
      - option: Python will warn you about the NameError, but since it is not important, you can ignore it
        correct: false
  - question: "True or False: Calling for the method print in a list (ls.print()) will throw an AttributeError"
    options:
      - option: "True"
        correct: true
      - option: "False"
        correct: false
  - question: |
      What type of error will you get when running the following code? 
      `
      my_ls = [] \n
      my_ls.remove(1)
      `
    options:
      - option: ValueError
        correct: true
      - option: IndexError
        correct: false
      - option: KeyError
        correct: false
      - option: AttributeError
        correct: false
      - option: It will not throw any error
        correct: false
  - question: Your code threw an error. Which of the following are steps to debug it?
    options:
      - option: Read the error message
        correct: true
      - option: Traceback the error to find the problematic line?
        correct: true
      - option: Go straight to ask for help
        correct: false
      - option: Google the error shown in the console
        correct: true
      - option: Give up and wait for it to solve by itself
        correct: false
      - option: Start again from scratch avoiding the same error
        correct: false
  - question: Select everything True about the debugger tool
    options:
      - option: As soon as you see an error, you should open the debugger
        correct: false
      - option: It is only available in VSCode
        correct: false
      - option: You can set as many Break Points (limited by the number of lines of your code) as you want
        correct: true
      - option: The Debug Console only shows the values of the variables at a specific Break Point
        correct: false
      - option: The same Break Point will be accessed only once
        correct: false
  - question: Which of the following are NOT a Python error?
    options:
      - option: KeyboardInterrupt
        correct: false
      - option: IndentationError
        correct: false
      - option: ComplexityError
        correct: true
      - option: ImportError
        correct: false
      - option: MouseInterrupt
        correct: true
      - option: InfiniteLoopError
        correct: true
