id: 891e6afd-f4c6-4b14-aae1-42a8e9e059fa
name: EC2 Instances
questions:
- answer: You can check what is taking up the space on the drive by install a small
    package ncdu. One installed run ncdu from the root directory to see the file sizes
    of all files. Then using rm -rf <name of the folder> to remove the corresponding
    folder to free up space on the drive.
  created_at: '2022-02-02 03:39:10'
  id: 743b4420-dc91-4400-88af-33b690a7b1fc
  question: My EC2 instance is too full to run my Docker image
- answer: 'This can be due to a mismatch between the chromedriver version and the
    version of chrome. Change the Dockerfile line where you specifiy the chromedriver
    version to a version compatible with your version of chrome. '
  created_at: '2022-02-02 03:39:10'
  id: 5fc3328e-9023-4e5d-aa9b-78cdd6303c54
  question: 'My Scraper Docker container returns the error "Time out receiving message
    from the renderer" when trying to run the container in headless on EC2. '
- answer: 'Make sure that you are writing the command correctly. The command will
    look like "scp -i <directory to key> <directory to the file you want to copy>
    ubuntu@ec2-xx-xx-xxx-xxx.compute-1.amazonaws.com:<directory where you want to
    save the file in the EC2 instance>"


    Then, you need to go to the directory where you saved the file to check if it''s
    there '
  created_at: '2022-02-02 03:39:10'
  id: b047afbc-876f-4af5-afa9-d49cf8cb6147
  question: 'I''m trying to upload a file that I created to the EC2 Cloud server.
    It says that it has been uploaded, but when I use ''ls'' on the EC2 terminal,
    the file has not been uploaded as expected. '
- answer: "Docker images or EC2 instances don't support any sort of GUI applications,\
    \ so you need to set headless mode. However, that might not be enough, you have\
    \ to allow your browser use your mouse, so you need to use the no-sandox option\n\
    The last issue you might find, is that, when you use Chrome in selenium, it tries\
    \ to store all the information in a directory called dev/shm, but if that's not\
    \ enough, Chrome will crash. To avoid it, you can use a workaround that will store\
    \ the info in a temporary file. \n\nSo, the code you should add when creating\
    \ the webdriver should look like this:\n\nfrom selenium import webdriver\nfrom\
    \ selenium.webdriver.chrome.options import Options\n\nchrome_options = Options()\n\
    chrome_options.add_argument('--headless')\nchrome_options.add_argument('--no-sandbox')\n\
    chrome_options.add_argument('--disable-dev-shm-usage')\n\ndriver = webdriver.Chrome('/path/to/your_chrome_driver_dir/chromedriver',\
    \ chrome_options=chrome_options)"
  created_at: '2022-02-02 03:39:10'
  id: 5a4d725d-7528-444f-a1a7-90c8d56c336f
  question: 'When I run my scraper locally, it works fine. Even when I run a container
    using selenium, it works without any issue. However, when I run it on an EC2 instance,
    I receive the following error: "devToolsActivePort file doesn''t exist" '