name: SQL - Subqueries
questions:
  - options:
      - correct: false
        option: SELECT
      - correct: true
        option: FROM
      - correct: true
        option: WHERE
      - correct: true
        option: HAVING
    question: Subqueries can be used inside
  - options:
      - correct: true
        option: 'True'
      - correct: false
        option: 'False'
    question: WITH can be used with more than one table
