- id: 492e6d3b-f25d-4350-981f-d32426d0dd5d
  name: Create a AWS Lex Chatbot with custom

- name: Investigate the other Amazon Services.
  id: 5394339a-8ec6-40b9-865a-e1e71e1b5cc9
  description: |
    1. Open Amazon Polly and try out the voices and changing the input text.
    2. Go to Amazon Textract look at the results of the example.
    3. Take a screenshot or a website and save it. 
    4. Upload the document to Textract and see how accurate it extract the information.
    5. Go to Amazon Comprehend look at the example as see how accurate the labels are.
    6. Have a look at the medical example as well(left side bar Comprehend Medical).
    7. Find some text from an article on the internet that you are interested in and copy the text.
    8. Paste the text into Comprehend and check out the analysis of the results. 
