- id: cd348bbe-1d06-4a4d-82cb-05990f2cdf34
  name: Custom standalone Kubeflow component
  description: |
    - Create a custom `Component` WITHOUT `python function`__ (e.g. as a standalone program with custom `Dockerfile` and `yaml` specification) [here](https://www.kubeflow.org/docs/components/pipelines/sdk/component-development/). This approach allows us for:
    - Easier customization of `Dockerfile` (although one can almost always deploy `image` beforehand and use it from within `python`)
    - Custom `.yaml` file - this one is harder to obtain with `python` functions (e.g. dependent values on `envvars` etc.)
    - __Make sure you have read and understood this part!__

- id: c8e2716a-20e1-462f-b59f-d877e017da75
  name: Recursion with Kubeflow DSL
  description: |
    Check what is required to use `recursion` with `kubeflow`'s `dsl` [here](https://www.kubeflow.org/docs/components/pipelines/sdk/dsl-recursion/)

- id: 2b6e76d4-7487-4382-8694-d6afefbea4ac
  name: Sidecar Injection
  description: |
    Check out [`sidecar injection`](https://istio.io/latest/blog/2019/data-plane-setup/) pattern (used by `istio`). What is it, why is it useful?

- id: 4ae54796-69fa-44c7-89cf-b9b4a84a5a69
  name: Kubeflow Kale
  description: |
    Check out [`kubeflow-kale`](https://github.com/kubeflow-kale/kale) as an even simpler way to define `kubeflow` pipelines.

- id: 43465898-1a3b-4f92-8f05-4103c9e56f1f
  name: More on defining pipelines in DSL
  description: |
    Go through [`kfp.dsl`](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html) documentation. What others methods could you use to the define the `pipeline`? Check out [parallel loop](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.ParallelFor)

- id: e85adba6-9d93-4f70-9fbe-b8611408215d
  name: Kubeflow Pipelines Metrics
  description: |
    Check how to create `metrics` as a part of `pipeline` or as a `component` [here](https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/). Which option (`pipeline` or `component`) should be preferred? 

- id: 06647db2-bcf3-4f76-ab28-a4d403630af2
  name: Static Type Checking
  description: |
    Check out [static type checking](https://www.kubeflow.org/docs/components/pipelines/sdk/static-type-checking/). How could one utilize it for increased robustness of the pipeline?