name: Kubernetes Workloads
questions:
  - question: Kubenetes implements its own networking model
    options:
      - option: "True"
        correct: false
      - option: "False"
        correct: true
  - question: hat is the name of the object that is used to, in conjunction with a controller, manage incoming traffic to workloads?
    options:
      - option: Service
        correct: false
      - option: Deployment
        correct: false
      - option: Ingress
        correct: true
      - option: ReplicaSet
        correct: false
      - option: ClusterIP
        correct: false
      - option: NodePort
        correct: false
  - question: What is a load balancer, and how does LoadBalancer work?
    options:
      - option: It exposes the service only to the outside world
        correct: false
      - option: It exposes the service only within the cluster
        correct: false
      - option: It is a service that is used to load balance traffic
        correct: true
      - option: It balances the traffic between the outside world and the cluster
        correct: true
  - question: What of the following are NOT types of services?
    options:
      - option: ClusterIP
        correct: false
      - option: NodePort
        correct: false
      - option: Networking
        correct: true
      - option: Ingress
        correct: true
      - option: LoadBalancer
        correct: false
      - option: ExternalName
        correct: true
  - question: What specs can you add to the Service resource?
    options:
      - option: clusterIPs
        correct: true
      - option: externalName
        correct: true
      - option: ingress
        correct: false
      - option: type
        correct: true
      - option: ports
        correct: true
      - option: selector
        correct: true
