name: K Nearest Neighbours
questions:
  - question: Select everything true about KNN
    options:
      - option: KNN is a supervised learning algorithm
        correct: true
      - option: KNN does more computation on training time rather than on testing time
        correct: true
      - option: KNN can be used for classification
        correct: true
      - option: KNN can be used for regression
        correct: true
      - option: KNN performs much better if the data is scaled
        correct: true
  - question: Which of the following is a distance metric that can be used in KNN?
    options:
      - option: Minkowski distance
        correct: true
      - option: Manhattan distance
        correct: true
      - option: Jaccard
        correct: true
      - option: Cosine distance
        correct: false
  - question: In terms of bias and variance, what is true about KNN?
    options:
      - option: Increasing the number of neighbors will increase the bias
        correct: true
      - option: Increasing the number of neighbors will decrease the bias
        correct: false
      - option: Increasing the number of neighbors will increase the variance
        correct: false
      - option: Increasing the number of neighbors will decrease the variance
        correct: true
      - option: Increasing the number of neighbors will not change the bias or variance
        correct: false
  - question: In sklearn, which module do you use to create a KNN class?
    options:
      - option: Linear_model
        correct: false
      - option: Classifier
        correct: false
      - option: decomposition
        correct: false
      - option: impute
        correct: false
      - option: neighbors
        correct: true
      - option: model_selection
        correct: false
      - option: trees
        correct: false
      

    