name: Class Decorators
questions:
  - question: What are the motivations for using Class Decorators?
    options:
      - option: Adding a different behaviour for methods
        correct: true
      - option: Adding convenient ways to create a class
        correct: true
      - option: Changing the default 'self' reference of the methods
        correct: true
      - option: As the name suggests, decorating the class with print statements
        correct: false
      - option: Creating the class given a different data type as the one given in the constructor
        correct: true
  - question: Select everything true about class methods and static methods
    options:
      - option: The first argument of class methods, by convention, is self
        correct: false
      - option: The first argument of static methods, by convention, is self
        correct: false
      - option: Static methods can be called without instantiate an object
        correct: true
      - option: Static methods can be called within a class method
        correct: true
      - option: Class methods are called from an instance
        correct: false
  - question: What functions does the property decorator add to an attribute?
    options:
      - option: getter
        correct: true
      - option: creator
        correct: false
      - option: iterator
        correct: false
      - option: setter
        correct: true
      - option: updater
        correct: false
      - option: deleter
        correct: true