name: Data Cleaning in Pandas
questions:
  - question: What are the motivations of cleaning your data? Select ALL that apply
    options:
      - option: Dirty data can affect the performance of the model 
        correct: true
      - option: A Pandas DataFrame can't work with dirty data
        correct: false
      - option: Having some missing values in a few rows can't be processed by your model
        correct: true
      - option: It can potentially lead to poor business decissions
        correct: true
      - option: Strings can't be directly processed by a simple ML model
        correct: true
      - option: Having a consistent structure allows you to put your data in a database with minimal effort
        correct: true
      - option: None, it is an aesthetics preference.
        correct: false
  - question: What steps are involved in Data Cleaning?
    options:
      - option: Handle missing data
        correct: true
      - option: Remove inconsistencies
        correct: true
      - option: Analysing the model's output
        correct: false
      - option: Loading the data to a database
        correct: false
      - option: Remove duplicates
        correct: true
      - option: Extract the data from an API, database, or a webpage
        correct: false
      - option: Filter unwanted outliers
        correct: true
      - option: Validate the data
        correct: true
  - question: Select everything True about the describe method in Pandas.
    options:
      - option: You can add the argument datetime_is_numeric
        correct: true
      - option: It works for both DataFrames and Series
        correct: true
      - option: It always shows the count value
        correct: true
      - option: It always shows the mean value
        correct: false
      - option: It always shows the unique value
        correct: false
      - option: You can specify whether to exclude certain columns based on their dtype
        correct: true
      - option: In many cases, it returns the same output as info
        correct: false
  - question: Select everything True about the info method in Pandas.
    options:
      - option: It works for both DataFrames and Series
        correct: true
      - option: It shows the number of non-null values in each column
        correct: true
      - option: You can specify whether to consider the non-null values in its count
        correct: true
      - option: By default, it shows you the memory usage
        correct: false
      - option: In many cases, it returns the same output as describe
        correct: false
      - option: This method can send the output directly to a buffer for further processing
        correct: true
  - question: How to group DataFrame df containing columns A, B, C, D by values contained in columns A and B and take the mean of those groups?
    options:
    - correct: false
      option: df.group("A").mean().groupby("B")
    - correct: false
      option: 'df.groupby("A", "B").apply(lambda value, row: value / len(row))'
    - correct: false
      option: df.group(["A", "B"]).mean()
    - correct: true
      option: df.groupby(["A", "B"]).mean()
  - question: What does aggregate do and where can it be applied on?
    options:
      - correct: true
        option: Aggregate using one or more operations over the specified axis.
      - correct: false
        option: Display aggregated statistics over specified axis
      - correct: false
        option: Used on pd.DataFrame
      - correct: false
        option: Used on pd.Series and groupby object
      - correct: true
        option: Available for all core objects (DataFrame, Series, Group object)