name: Regression Trees
questions:
  - question: What metrics should you use to measure the quality of a split in a Regression tree?
    options:
      - option: Gini impurity
        correct: false
      - option: Variance impurity
        correct: false
      - option: Mean Squared Error
        correct: True
      - option: Mean Absolute Error
        correct: True
      - option: Entropy
        correct: False
      - option: Information Gain
        correct: False
  - question: Which of the following are features of a Regression tree?
    options:
      - option: The number of leaves
        correct: true
      - option: The number of nodes
        correct: true
      - option: The number of splits
        correct: true
      - option: The number of features
        correct: false
      - option: The number of samples
        correct: false
  - question: "True or False: Regression and Classification Trees make the same type of split differing only in the metric they are based on"
    options:
      - option: "True"
        correct: True
      - option: "False"
        correct: False
  - question: What parameters can you include in the DecisionTreeRegressor in sklearn?
    options:
      - option: criterion
        correct: true
      - option: max_depth
        correct: true
      - option: max_features
        correct: true
      - option: classes
        correct: false
      - option: n_classes
        correct: false
      - option: random_state
        correct: true
  - question: What methods can you include in the DecisionTreeRegressor in sklearn?
    options:
    - option: apply
      correct: true
    - option: decision_path
      correct: true
    - option: fit_transform
      correct: false
    - option: transform
      correct: false
    - option: predict_proba
      correct: false