name: Kubernetes Basics
questions:
  - question: Which of the following are features of Kubernetes? Select all that apply.
    options:
      - option: Self-healing
        correct: true
      - option: Horizontally Scalable
        correct: true
      - option: Batch Execution
        correct: true
      - option: Secrets and configuration management
        correct: true
  - question: Which of the following components runs on each node and ensures containers are running in a pod?
    options:
      - option: kubelet
        correct: true
      - option: kube-proxy
        correct: false
      - option: etcd
        correct: false
      - option: worker
        correct: false
      - option: controller
        correct: false
      - option: scheduler
        correct: false
      - option: pod
        correct: false
  - question: Which of the following components manages the assigning nodes to pods depending on the available resources?
    options:
      - option: kubelet
        correct: false
      - option: kube-proxy
        correct: false
      - option: etcd
        correct: false
      - option: worker
        correct: false
      - option: controller
        correct: false
      - option: scheduler
        correct: true
      - option: pod
        correct: false
  - question: Which of the following resources are not associated to any namespace?
    options:
      - option: DaemonSets
        correct: true
      - option: Pods
        correct: false
      - option: PersistentVolumes
        correct: true
      - option: Workloads
        correct: false
      - option: Services
        correct: false
      - option: Nodes
        correct: true

  - question: "True or False: You can write kubernetes configuration files in json format"
    options:
      - option: "True"
        correct: true
      - option: "False"
        correct: false
  - question: Which of the following commands are NOT a kubectl command?
    options:
      - option: get
        correct: false
      - option: create
        correct: false
      - option: apply
        correct: false
      - option: pod
        correct: true
      - option: sync
        correct: true
      - option: diff
        correct: false
      
