name: 4.1.0 MLFlow
questions:
  - options:
      - correct: true
        option: Staging - we're preparing a model to serve users
      - correct: false
        option: Staging - the model is being served to users
      - correct: false
        option: Staging - the model is being served to customers who have early access
      - correct: false
        option: Alpha - the model is being served to customers who have early access
      - correct: false
        option: Alpha - this is the primary model in use
      - correct: true
        option: Production - the model is being served to users
      - correct: false
        option: Production - the model is currently under production, and we're preparing
          for it to serve users
      - correct: true
        option: Archived - the model has reached the end of it's lifecycle
      - correct: false
        option: Archived - we're preparing a model to serve users and will soon remove
          it from the archive
      - correct: true
        option: None - the model has no stage
    question: Which of the following are predefined model stage names and are accompanied
      by their correct description?
  - options:
      - correct: true
        option: The environment variable MLFLOW\_TRACKING\_URI must be defined on
          your system
      - correct: true
        option: A MLFlow server must be running on the specified tracking URI
      - correct: true
        option: The endpoint of the server running the model registry can be overwritten
          in Python
      - correct: false
        option: The MLFlow tracker must be running locally, not remotely
      - correct: true
        option: We can specify the artifact store as a remote S3 bucket
      - correct: true
        option: The artifact store is where models and other files generated by project
          runs should be saved
      - correct: true
        option: The backend store is a database where run metadata and metrics are
          logged
      - correct: false
        option: We can log metrics, artifacts and models from python outside of a
          mlflow run context, as well as within one
      - correct: false
        option: Only one person should access the model registry at any one point
      - correct: false
        option: The model registry should be shared with other team members by pushing
          the files to GitHub
    question: Which of the following are true about running an MLFlow model registry
