name: 2.3.1 Binary Classification
questions:
  - options:
      - correct: true
        option: Labels are discrete for classification data, but not for regression
          data
      - correct: true
        option: Labels are categorical for classification data, but not for regression
          data
      - correct: false
        option: Labels are continuous for classification data, but not for regression
          data
      - correct: false
        option: Features can be categorical for classification data, but not for regression
          data
      - correct: false
        option: Features can be discrete for classification data, but not for regression
          data
      - correct: false
        option: Features can be continuous for classification data, but not for regression
          data
      - correct: false
        option: Features can be continuous for regression data, but not for classification
          data
    question: Which of the following are true about the format of data in classification
      problems?
  - options:
      - correct: false
        option: Multiclass classification
      - correct: true
        option: Multilabel classification
      - correct: true
        option: Binary classification
      - correct: false
        option: Anywhere where output values for a single example are independent
          and have to be transformed into probabilities within (0, 1) range
    question: Where can the Binary Cross Entropy loss function be used?
  - options:
      - correct: true
        option: Squashes logits into (0, 1) range
      - correct: true
        option: Transforms logits into probability values
      - correct: false
        option: Transforms probabilities into logits
      - correct: false
        option: The outputs for a single example have to sum to one
      - correct: true
        option: Is used to obtain probabilities in binary logistic regression
      - correct: true
        option: Is also known as the logistic sigmoid
      - correct: true
        option: Is a smoothed step function
    question: Mark everything true about the sigmoid function
  - options:
      - correct: false
        option: Unnormalized probability contained in (-1, 1) range
      - correct: true
        option: Unnormalized probability contained in (-inf, +inf) range
      - correct: false
        option: Another name for probability
      - correct: true
        option: Also known as log odds
    question: What are logits?
  - options:
      - correct: true
        option: It is a classification model
      - correct: true
        option: It is equivalent to linear regression with a sigmoid layer added on
          the end
      - correct: false
        option: It's outputs are discrete values
      - correct: false
        option: It outputs a two-vector, with one element for the positive class and
          one for the negative
      - correct: true
        option: It's outputs quantify the certainty of the prediction
      - correct: true
        option: Even though the hypothesis is nonlinear, we refer to it as a linear
          model
      - correct: true
        option: The decision boundary for a logistic regression model is a straight
          line (or hyperplane)
    question: Select everything true about logistic regression
