name: Intro to Docker
questions:
  - options:
      - correct: true
        option: Easy to share and load applications from others
      - correct: true
        option: Less steps to get everything set up
      - correct: true
        option: Consistent deployment of applications across environments
      - correct: true
        option: Applications can run on any machine, regardless of dependencies, as long as you have docker
    question: Which of the following are motivations for using Docker?
  - options:
      - correct: false
        option: An image is an instance of a container
        reason: A container is an instance of an image
      - correct: true
        option: If an image cannot be found locally, Docker will try to pull it from Docker Hub
      - correct: true
        option: They are built from a Dockerfile
    question: Select all options which are true about Docker images
  - options:
      - correct: true
        option: All Dockerfiles start with the FROM instruction
      - correct: false
        option: All Dockerfiles end with the ENTRYPOINT instruction
      - correct: false
        option: Docker run creates containers by running the Dockerfile
      - correct: true
        option: Dockerfiles contain the instructions for how to build an image
      - correct: true
        option: Dockerfiles must always have the exact name "Dockerfile"
    question: Which of the following statements about Dockerfiles are true?
  - options:
      - correct: false
        option: If you don't specify a name for a container, you won't be able to reference it by name
        reason: Docker creates a random name by combining two random words with an underscore
      - correct: false
        option: You can run multiple containers at the same time as long as they have the same name
      - correct: true
        option: Containers are instances of images
      - correct: false
        option: You can pull and push containers to Docker hub
    question: Which of the following statements about containers are true?
